version: '3'
services:
        selenium-chrome:
                restart: always
                image: selenium/standalone-chrome
                container_name: yandex_parser_by_keywords_selenium
                ports:
                        - "4444:4444"